import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { pathToFileURL } from 'node:url';
export const ADMIN='11111111-1111-4111-8111-111111111111';
export const PRODUCT='22222222-2222-4222-8222-222222222222';
export const EVENT='33333333-3333-4333-8333-333333333333';
export const TICKET='44444444-4444-4444-8444-444444444444';
export async function makeDatabase(){
  const db=new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create schema storage;
  create function auth.uid() returns uuid language sql stable as $$select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid$$;
  create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role'$$;
  grant usage on schema auth to anon,authenticated,service_role;
  create table auth.users(id uuid primary key);
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
  alter table storage.objects enable row level security;
  grant usage on schema public to anon,authenticated,service_role;`);
  for(const path of ['20260912002550_site_content_backend.sql','20260912011417_site_management_commerce.sql','20260912012555_paypal_order_lifecycle.sql','20260912234519_notification_signups_and_outbox.sql','20260913000629_event_external_ticketing.sql'])await db.exec(await readFile(new URL(`../supabase/migrations/${path}`,import.meta.url),'utf8'));
  await db.exec(`insert into auth.users values ('${ADMIN}');insert into public.site_admins(user_id)values('${ADMIN}');
  insert into public.events(id,title,date,status,city,venue)values('${EVENT}','Concierto de prueba QA','2099-12-15','Publicado','Santo Domingo','Sala de pruebas');
  insert into public.products(id,title,status,price,currency,capacity,sale_mode,image_url,description,category,variant)values('${PRODUCT}','Camiseta del universo · prueba','Publicado',25,'USD',3,'both','https://riccie-oriach.vercel.app/assets/images/riccie-portrait.jpg','Una pieza de prueba para verificar pedidos.','Merch','M');
  insert into public.ticket_types(id,event_id,title,status,price,currency,capacity,sale_mode)values('${TICKET}','${EVENT}','General · prueba','Publicado',40,'USD',2,'both');`);
  let sequence=Promise.resolve();
  const as=async(role,callback,sub=role==='authenticated'?ADMIN:null)=>{
    const job=sequence.then(async()=>{await db.exec('begin');try{await db.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({role,...(sub?{sub}:{})})]);await db.exec(`set local role ${role}`);const result=await callback(db);await db.exec('commit');return result;}catch(error){await db.exec('rollback');throw error;}});sequence=job.catch(()=>{});return job;
  };
  return {db,as};
}
async function tests(){
  const {db,as}=await makeDatabase();let checks=0;
  const ok=(value)=>{assert.ok(value);checks++;};
  const rejects=async(fn,pattern)=>{await assert.rejects(fn,pattern);checks++;};
  const customer=(email='qa@example.test')=>({name:'Prueba QA',email,phone:'0000000000',note:'Datos ficticios de prueba'});
  const item=(id=PRODUCT,quantity=1,kind='product')=>({id,kind,quantity,unit_price:0});
  const submit=(items=[item()],key=crypto.randomUUID(),email)=>as('anon',async(d)=>(await d.query('select public.submit_order($1::jsonb,$2::jsonb,$3::uuid) as value',[JSON.stringify(customer(email)),JSON.stringify(items),key])).rows[0].value);
  const row=async(id)=>(await db.query('select * from public.orders where id=$1',[id])).rows[0];
  const stock=async(id=PRODUCT)=>(await db.query('select allocated from public.products where id=$1',[id])).rows[0].allocated;
  const manage=async(id,next,payment='pending')=>{const o=await row(id);return as('authenticated',async(d)=>(await d.query('select to_jsonb(public.manage_order($1,$2,$3,$4,$5)) as value',[id,next,'Revisado QA',payment,o.updated_at])).rows[0].value);};
  const key=crypto.randomUUID(),order=await submit([item()],key);
  ok(order.total===25);ok(await stock()===0);ok((await submit([item()],key)).id===order.id);
  await rejects(()=>submit([item(PRODUCT,11)]),/cantidad/);
  await rejects(()=>submit([item(),item()]),/repetido/);
  await rejects(()=>submit([item(),item(TICKET,1,'ticket')]),/separadas/);
  await rejects(()=>as('anon',(d)=>d.query('select * from public.orders')),/permission denied/);
  await rejects(()=>as('anon',(d)=>d.query('select public.finish_payment($1,$2,$3,$4,$5,$6)',[order.id,'fake',25,'USD','paid',''])),/permission denied/);
  await rejects(()=>as('anon',(d)=>d.query('select private.submit_order($1,$2,$3,$4)',[JSON.stringify(customer()),JSON.stringify([item()]),crypto.randomUUID(),'online'])),/permitida/);
  ok((await as('authenticated',(d)=>d.query('select * from public.orders'), '55555555-5555-4555-8555-555555555555')).rows.length===0);
  await rejects(()=>as('authenticated',(d)=>d.query("update public.products set allocated=0")),/permission denied/);
  const confirmed=await manage(order.id,'Confirmado');ok(confirmed.status==='Confirmado');ok(await stock()===1);
  await rejects(()=>as('authenticated',(d)=>d.query('select public.manage_order($1,$2,$3,$4,$5)',[order.id,'Cancelado','','pending','2000-01-01'])),/cambió/);
  const other=await submit([item(PRODUCT,2)],crypto.randomUUID(),'qa2@example.test');await manage(other.id,'Confirmado');ok(await stock()===3);
  const waiting=await manage(order.id,'Cancelado');ok(waiting.status==='Cancelado');ok(await stock()===2);
  await rejects(()=>manage(order.id,'Confirmado'),/permite/);
  const oversell=await submit([item()],crypto.randomUUID(),'qa3@example.test');
  const rival=await submit([item()],crypto.randomUUID(),'qa4@example.test');await manage(oversell.id,'Confirmado');
  await rejects(()=>manage(rival.id,'Confirmado'),/disponibilidad/);ok(await stock()===3);
  await manage(other.id,'Cancelado');await manage(oversell.id,'Cancelado');ok(await stock()===0);
  await db.exec("update public.events set ticket_status='cancelled'");await rejects(()=>submit([item(TICKET,1,'ticket')],crypto.randomUUID(),'qaticket@example.test'),/acepta reservas/);await db.exec("update public.events set ticket_status='available'");
  await db.query("update public.events set ticket_provider='Tix', ticket_url='https://tickets.example.test/show', ticket_availability='Quedan 12 · VIP agotado'");
  ok((await db.query('select ticket_status from public.events')).rows[0].ticket_status==='available');
  await rejects(()=>db.query("update public.events set ticket_url='http://tickets.example.test/show'"),/check constraint/);
  await rejects(()=>db.query("update public.events set ticket_availability=repeat('x',161)"),/check constraint/);
  await db.query("update public.events set ticket_status='coming_soon'");
  ok((await db.query('select ticket_status from public.events')).rows[0].ticket_status==='coming_soon');
  await db.query("update public.events set ticket_status='available'");
  await rejects(()=>submit([item(TICKET,1,'ticket')],crypto.randomUUID(),'qaticket@example.test'),/plataforma externa/);
  await rejects(()=>as('service_role',async(d)=>(await d.query('select public.prepare_checkout($1,$2,$3) as value',[JSON.stringify(customer('online-ticket@example.test')),JSON.stringify([item(TICKET,1,'ticket')]),crypto.randomUUID()])).rows[0].value),/plataforma externa/);
  ok((await db.query('select allocated from public.ticket_types where id=$1',[TICKET])).rows[0].allocated===0);
  await rejects(()=>as('anon',(d)=>d.query('select * from public.ticket_types')),/permission denied/);
  await rejects(()=>as('authenticated',(d)=>d.query('select * from public.ticket_types'),ADMIN),/permission denied/);
  await rejects(()=>as('service_role',(d)=>d.query('select * from public.ticket_types')),/permission denied/);
  ok((await db.query("select count(*)::int as count from public.orders where kind='ticket'")).rows[0].count===0);
  const online=await as('service_role',async(d)=>(await d.query('select public.prepare_checkout($1,$2,$3) as value',[JSON.stringify(customer('paypal@example.test')),JSON.stringify([item()]),crypto.randomUUID()])).rows[0].value);ok(await stock()===1);
  await rejects(()=>manage(online.id,'Confirmado','paid'),/PayPal/);
  await as('service_role',(d)=>d.query('select public.begin_capture($1)',[online.id]));
  await rejects(()=>as('service_role',(d)=>d.query('select public.finish_payment($1,$2,$3,$4,$5,$6)',[online.id,'CAPTURE1',1,'USD','paid',''])),/coincide/);
  const finish=()=>as('service_role',(d)=>d.query('select public.finish_payment($1,$2,$3,$4,$5,$6)',[online.id,'CAPTURE1',25,'USD','paid','']));await finish();await finish();ok(await stock()===1);ok((await row(online.id)).payment_status==='paid');
  await manage(online.id,'Entregado','paid');ok((await row(online.id)).status==='Entregado');
  const expiring=await as('service_role',async(d)=>(await d.query('select public.prepare_checkout($1,$2,$3) as value',[JSON.stringify(customer('expire@example.test')),JSON.stringify([item()]),crypto.randomUUID()])).rows[0].value);
  await db.query("update public.orders set hold_expires_at=now()-interval '1 minute' where id=$1",[expiring.id]);await as('anon',(d)=>d.query('select public.expire_checkouts()'));ok((await row(expiring.id)).status==='Cancelado');ok(await stock()===1);
  const draft='66666666-6666-4666-8666-666666666666';await db.query("insert into products(id,title,capacity) values($1,'Borrador',2)",[draft]);ok((await as('anon',(d)=>d.query('select id from products where id=$1',[draft]))).rows.length===0);await rejects(()=>submit([item(draft)],crypto.randomUUID(),'draft@example.test'),/disponible/);
  console.log(`Commerce database: ${checks} assertions passed (real PostgreSQL via PGlite).`);await db.close();
}
if(import.meta.url===pathToFileURL(process.argv[1]).href)await tests();
